services:
  - type: web
    name: qrib-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: FLASK_APP
        value: run.py
      - key: FRONTEND_URL
        value: https://qrib-mu.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ADMIN_SEED_SECRET
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_CALLBACK_URL
        value: https://qrib-f4sk.onrender.com/api/payments/mpesa/callback
      - key: RESEND_API_KEY
        sync: false
