"""add semester availability fields to properties

Revision ID: 04df95d85dfa
Revises: 793c658f73ee
Create Date: 2026-09-04 00:30:35.644998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04df95d85dfa'
down_revision = '793c658f73ee'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='available_from')
            THEN ALTER TABLE properties ADD COLUMN available_from VARCHAR(20);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='available_to')
            THEN ALTER TABLE properties ADD COLUMN available_to VARCHAR(20);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='semester_label')
            THEN ALTER TABLE properties ADD COLUMN semester_label VARCHAR(50);
            END IF;
        END $$;
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('semester_label')
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###
