"""add semester availability fields to properties

Revision ID: 04df95d85dfa
Revises: 793c658f73ee
Create Date: 2026-09-04 00:30:35.644998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04df95d85dfa'
down_revision = '793c658f73ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semester_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('semester_label')
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###
