"""add payouts table and mpesa_phone to users

Revision ID: 511a2c3eee11
Revises: dce88709084e
Create Date: 2026-09-04 11:37:37.702870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511a2c3eee11'
down_revision = 'dce88709084e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mpesa_phone')

    # ### end Alembic commands ###
