"""add water and electricity cost to properties

Revision ID: 793c658f73ee
Revises: 6b2c3d4e5f6a
Create Date: 2026-09-04 00:20:22.206658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793c658f73ee'
down_revision = '6b2c3d4e5f6a'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # Add payments columns only if they don't exist
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='transaction_id')
            THEN ALTER TABLE payments ADD COLUMN transaction_id VARCHAR(120);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='gateway_response')
            THEN ALTER TABLE payments ADD COLUMN gateway_response TEXT;
            END IF;
        END $$;
    """))
    # Add properties columns only if they don't exist
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='water_cost')
            THEN ALTER TABLE properties ADD COLUMN water_cost NUMERIC(10,2) DEFAULT 0;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='electricity_cost')
            THEN ALTER TABLE properties ADD COLUMN electricity_cost NUMERIC(10,2) DEFAULT 0;
            END IF;
        END $$;
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('electricity_cost')
        batch_op.drop_column('water_cost')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
