"""add water and electricity cost to properties

Revision ID: 793c658f73ee
Revises: 6b2c3d4e5f6a
Create Date: 2026-09-04 00:20:22.206658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793c658f73ee'
down_revision = '6b2c3d4e5f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['checkout_request_id'])

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('electricity_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('electricity_cost')
        batch_op.drop_column('water_cost')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
