"""add reset token fields to users

Revision ID: 9837903cf7fc
Revises: 04df95d85dfa
Create Date: 2026-09-04 01:12:09.611264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9837903cf7fc'
down_revision = '04df95d85dfa'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='reset_token')
            THEN ALTER TABLE users ADD COLUMN reset_token VARCHAR(255);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='reset_token_expires')
            THEN ALTER TABLE users ADD COLUMN reset_token_expires TIMESTAMPTZ;
            END IF;
        END $$;
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
