"""add message_type to messages

Revision ID: d2c6e5ffa7df
Revises: a5c2f9ce8f11
Create Date: 2026-09-03 13:20:47.036452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c6e5ffa7df'
down_revision = 'a5c2f9ce8f11'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=30), nullable=False, server_default='text'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
