"""add latitude longitude to properties

Revision ID: dce88709084e
Revises: 9837903cf7fc
Create Date: 2026-09-04 01:22:20.371999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce88709084e'
down_revision = '9837903cf7fc'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='latitude')
            THEN ALTER TABLE properties ADD COLUMN latitude NUMERIC(10,7);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='longitude')
            THEN ALTER TABLE properties ADD COLUMN longitude NUMERIC(10,7);
            END IF;
        END $$;
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
