"""add latitude longitude to properties

Revision ID: dce88709084e
Revises: 9837903cf7fc
Create Date: 2026-09-04 01:22:20.371999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce88709084e'
down_revision = '9837903cf7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
